name: studrasp_requiem
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_riverpod: ^2.0.0-dev.9
  day_night_time_picker: ^1.1.2

  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lints: ^2.0.0

  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_gen_runner: ^4.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
