// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKcY3nI_q3vu6qdld20q5nAQiOWyO4zRg',
    appId: '1:138745531703:web:0cc38bed08c4347f7bdeb2',
    messagingSenderId: '138745531703',
    projectId: 'studrasp',
    authDomain: 'studrasp.firebaseapp.com',
    storageBucket: 'studrasp.appspot.com',
    measurementId: 'G-KYYKSJE2C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmW_koYlbDgK9fp0qktdzQqdLOZrjQhnY',
    appId: '1:138745531703:android:8589158a5108081c7bdeb2',
    messagingSenderId: '138745531703',
    projectId: 'studrasp',
    storageBucket: 'studrasp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMTmdX3qJSgTvj5xH2s5JMGV47qhnrYw',
    appId: '1:138745531703:ios:16d464c68e731ae07bdeb2',
    messagingSenderId: '138745531703',
    projectId: 'studrasp',
    storageBucket: 'studrasp.appspot.com',
    iosClientId: '138745531703-3nbkro2p78lck4rnq2pjatgl0a9fh1qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.studraspRequiem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWMTmdX3qJSgTvj5xH2s5JMGV47qhnrYw',
    appId: '1:138745531703:ios:16d464c68e731ae07bdeb2',
    messagingSenderId: '138745531703',
    projectId: 'studrasp',
    storageBucket: 'studrasp.appspot.com',
    iosClientId: '138745531703-3nbkro2p78lck4rnq2pjatgl0a9fh1qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.studraspRequiem',
  );
}
