// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQcor46_sBHYfwwMXbTP096BDgqfTpkwU',
    appId: '1:1009441715837:web:e29630663d6fea3c4ea314',
    messagingSenderId: '1009441715837',
    projectId: 'studrasp-4e58d',
    authDomain: 'studrasp-4e58d.firebaseapp.com',
    storageBucket: 'studrasp-4e58d.appspot.com',
    measurementId: 'G-WRWNEFE4C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZOC5MwBOmiI_pvSdxAxd38yUpb4Aehjs',
    appId: '1:1009441715837:android:74a9ceae8f81b7cb4ea314',
    messagingSenderId: '1009441715837',
    projectId: 'studrasp-4e58d',
    storageBucket: 'studrasp-4e58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Fj2Ltri5XMq8F7241WwUVNrQAd8JJyM',
    appId: '1:1009441715837:ios:93053946faa4c9eb4ea314',
    messagingSenderId: '1009441715837',
    projectId: 'studrasp-4e58d',
    storageBucket: 'studrasp-4e58d.appspot.com',
    iosClientId: '1009441715837-tm266kkhluckfp3mvqgk7ahkba1vjbm3.apps.googleusercontent.com',
    iosBundleId: 'com.null.zed.StudRasp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Fj2Ltri5XMq8F7241WwUVNrQAd8JJyM',
    appId: '1:1009441715837:ios:93053946faa4c9eb4ea314',
    messagingSenderId: '1009441715837',
    projectId: 'studrasp-4e58d',
    storageBucket: 'studrasp-4e58d.appspot.com',
    iosClientId: '1009441715837-tm266kkhluckfp3mvqgk7ahkba1vjbm3.apps.googleusercontent.com',
    iosBundleId: 'com.null.zed.StudRasp',
  );
}
